### ISSUE TITLE
The generated result is not desirable,what's the possible reason?

### ISSUE THREAD

**Issue by huan-zi** [ginobilinie/medSynthesis#11]
I 'm trying to generate CT from MRI with 3D vision, but the result doesn't look like  CT. It's like a label map,no details.And the loss is already changing a little.Have you met this problem?

**Comment by ginobilinie** [comment]
I suggest you use big patch, something like 144x144x16. It is relatively harder to train the model using small 3d patch.

**Comment by ginobilinie** [comment]
Also, I strongly suggest you use another copy of my code: https://github.com/ginobilinie/medSynthesisV1
