### ISSUE TITLE
Could not find the usage of the Auto-Context Model in your code.

### ISSUE THREAD

**Issue by Pro-flynn** [ginobilinie/medSynthesis#3]
I could not find the usage of the Auto-Context Model in your code as descrided in your paper(Medical Image Synthesis with Context-Aware Generative Adversarial Networks)? Please give some details about the ACM in your code . thanks!

**Comment by ginobilinie** [comment]
Hi, for auto-context model, we just need to concatenate the predicted target image with the source image, and set them together as the input to train the next GAN. I will update the source code to make it easier.
