### ISSUE TITLE
3T to 7T model

### ISSUE THREAD

**Issue by KingsleyBw** [ginobilinie/medSynthesis#5]
Hi, I just looked through your paper. I'm quite interested in the 3T to 7T part. It seems that the code published here is intended for MR-to-CT. Are you using the same code for 3T-to-7T training? Or do you have another version that you can share for the 3T-to-7T part for your paper?

**Comment by ginobilinie** [comment]
check this one (it is implemented by pytorch, and use U-Net like network with long-skip connection as generator, and we implemented original BCE loss and wgan-gp loss for the discriminator):

https://github.com/ginobilinie/medSynthesisV1
