### ISSUE TITLE
trouble to understand latent space

### ISSUE THREAD

**Issue by hnbonsou** [ginobilinie/medSynthesis#6]
Hi all,

Please, I am struggling to understand how the latent space is used in your code.
I would like to know how MRI patches are related to the latent space to synthesize the pseudo-CT. If one can consider that the distribution used to initialize the filters can be considered as the latent space.

Thank you in advance for your understanding.

**Comment by ginobilinie** [comment]
I'm confused what you mean, can you please specify it?

**Comment by hnbonsou** [comment]
I thought that the MRI patches should be somehow connected to a known distribution which is noise (commonly called the vector Z in the GAN formulation)  before to be introduced in the generator. 
Please, how is this connection established in your approach?

**Comment by hnbonsou** [comment]
Please for more precision, I put it on the graph attached
[scheme.pptx](https://github.com/ginobilinie/medSynthesis/files/2379104/scheme.pptx)

**Comment by rogertrullo** [comment]
Since we want to generate CT images with a one to one correspondance, we do not add any noise in the input, so the second graph in your ppt is more accurate

**Comment by hnbonsou** [comment]
Thank You a lot, I understand now.

**Comment by ginobilinie** [comment]
@hnbonsou  Roger's explanation is exactly what we mean. In addition, if it is one-to-more reflection, we can add some noise along with the input source image.

**Comment by hnbonsou** [comment]
@ginobilinie Thanks a lot for this clarification. I will go through that.
