### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tianlili1** [ginobilinie/medSynthesis#7]
Hi，I have read your article, the method proposed is very good, but there are a lot of problems when running the code, I hope you can help me, I have got access to the ADNI database, but I don't know how to download  the required data set, can you share the data set you use with me?

**Comment by ginobilinie** [comment]
For the code, I suggest you use the pytorch version (this TF version is written more than two years ago and a lot of functions have not been updated to the latest api):

https://github.com/ginobilinie/medSynthesisV1

For the data, I have no permission to share the data (I just have permission to use it). I'm very sorry for it.

**Comment by tianlili1** [comment]
Ok,Thank you for your repley.I will use the pytorch version.If I have a problem that I don’t understand, I hope you can help me with it.

**Comment by ginobilinie** [comment]
Sure.

**Comment by tianlili1** [comment]
Hi! I'm back again. In the paper you mentioned random forests to synthesize images. I have also seen this paper using random forest composite images. Do you have its source code? If so, can you share it with me at 770133167@qq.com? Thank you!

**Comment by ginobilinie** [comment]
you should ask the first author of that paper for the code. I cannot share other guys' code without their permission.

**Comment by lyc-lang** [comment]
Hi, I have applied for and obtained access to ADNI data set. I don't know how to get the two datasets used in the paper to evaluate the model. Could you please send me a link，thanks！

**Comment by lyc-lang** [comment]
Or could you share the training data set? This is my email: mirror_whut@qq.com

**Comment by rogertrullo** [comment]
Hi @lyc-lang the dataset used in the paper is private containing medical information and as such we cannot share it publicly.
