### ISSUE TITLE
why doesn't the 3D model contain a discriminator? 

### ISSUE THREAD

**Issue by NatalieZou** [ginobilinie/medSynthesis#9]
I read the 3D code and didn't find a discriminator in it. So isn't the 3D model an adversarial network?

**Comment by ginobilinie** [comment]
Check it: 

https://github.com/ginobilinie/medSynthesis/tree/master/3dganversion

**Comment by NatalieZou** [comment]
Thanks a lot!

**Comment by NatalieZou** [comment]
> Check it:
> 
> https://github.com/ginobilinie/medSynthesis/tree/master/3dganversion

I read this code carefully,  the discriminator seems to be useless, there is no optimizer of discriminator

**Comment by ginobilinie** [comment]
I'm now very busy for hunting for jobs. I cannot check it very carefully for you. After this period, I can find my previous codes (it was two years ago) and upload the correct one. For now you can use this one (this one has been tested by many others and it also contains 2d and 3d version): 

https://github.com/ginobilinie/medSynthesisV1

**Comment by ginobilinie** [comment]
@NatalieZou  You can also check this repository again, I update it:
https://github.com/ginobilinie/medSynthesis/tree/master/3dganversion

**Comment by NatalieZou** [comment]
@ginobilinie Thank you so much!
